### ISSUE TITLE
sporadic issue : application starts with serial number registration

### ISSUE THREAD

**Issue by nourmed** [MichaelKMalak/ixir_app#10]
application get stuck in Serial number registration of the bracelet and won't resolve only if you reinstall the app

**Comment by nourmed** [comment]
add button to exit the page / is there any verification for the serial number ?

**Comment by nourmed** [comment]
I recommend to remove all constraints ( only check for existence to not duplicate) and  add them later when @nourmed  suggests a method to generate the serial number.

**Comment by nourmed** [comment]
for @debugging : check firebase registered bracelets fisrt @MichaelKMalak  : pls qdd link to this issue

**Comment by MichaelKMalak** [comment]
https://github.com/MichaelKMalak/ixir_app/commit/cb445365bf63364de73fd2dc096dd13364d9677f
https://github.com/MichaelKMalak/ixir_app/commit/d917e81219998d043efd0e4295c93efbf769566b

**Comment by nourmed** [comment]
didn't observed it again => @fixed thnx @MichaelKMalak
