### ISSUE TITLE
invalid number

### ISSUE THREAD

**Issue by nourmed** [MichaelKMalak/ixir_app#7]
invalid number during registration phase

**Comment by nourmed** [comment]
static bool isPhoneNumber(String value) {
    if (isEmpty(value)) return false;
    return RegExp(r'^[0-9]{10,12}$').hasMatch(value);
==> change verfication method

**Comment by MichaelKMalak** [comment]
https://github.com/MichaelKMalak/ixir_app/commit/a74e1dd6dbd53038ef7c0288856f4469865a409f

**Comment by nourmed** [comment]
@fixed
